### ISSUE TITLE
Ambiguity on which lessons to contribute to for new instructor trainees

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/website-archive#691] opened 2017-04-12 17:05 UTC
I just got a lesson contribution from a trainee for one of the lessons marked "These lessons have been contributed by community members." on the /lessons/ page. It's not clear to me whether we have been accepting contributions to these lessons as part of trainee checkout. If we are accepting these contributions towards checkout, need clarification from the SWC SC or ED on policy. Else we need to explicitly state on that page that contributions to these lessons do not count towards instructor checkout.

@jduckles @ChristinaLK @raynamharris @smcclatchy @mkuzak @karinlag @weaverbel @k8hertweck @maneesha

**Comment by k8hertweck** [comment] 2017-04-12 17:17
I'm not clear on what precisely you mean. Could you link to one of the lessons in question?

**Comment by ErinBecker** [comment] 2017-04-12 17:20
https://github.com/katyhuff/python-testing
https://github.com/swcarpentry/capstone-novice-spreadsheet-biblio
https://github.com/DamienIrving/capstone-oceanography
(and more listed under https://software-carpentry.org/lessons/#contributed)

**Comment by ChristinaLK** [comment] 2017-04-12 17:54
This sounds like a question to run by the trainer's group.  I'll share my 2 cents there if that's the proper avenue.

**Comment by maneesha** [comment] 2017-04-12 17:56
I'd also like to hear lesson mainters input on this.  Ideally, I'd want trainee's checkout exercises to be contributions that actually help with maintaining and developing lessons.  So there would be some type of guidance around what kinds of contributions are needed and how they will be reviewed and merged.  Trainees' contributions can then follow those guidenlines.  This makes for more meaningful, relevant contributions --- otherwise it can feel like a rote homework assignment.

**Comment by jduckles** [comment] 2017-04-12 19:55
So I think there are two things going on here: 

1. it sounds like the trainee met the objective of going through the PR process to submit a contribution *yay*; 
2. they did it in the wrong place. 

I say we accept it this time and tighten up the instructions so we only get contributions to core lessons. I went and looked at the instructions, we only say to look at the lessons on https://software-carpentry.org/lessons

**Comment by ErinBecker** [comment] 2017-04-12 20:00
Agreed that we accept it this time. My question is whether we want to allow it in general. This seems like a policy decision, but I'm not sure who the right person to address it is. Me as director of instructor training? @jduckles as ED of SWC? The SWC SC?

**Comment by k8hertweck** [comment] 2017-04-12 20:32
My initial reaction was to ask what lessons they can teach during their example demos during checkout, which appears to be the same general list which appears allowable for exercise submissions. Have you had students do their demo using a contributed lesson? It would be nice to have allowable lessons consistent if there is a change. 

The truth is that we don't actually have procedures in place which dictate SWC's core/supported lessons, including how new are added and old removed (the exception is the lesson incubation proposal, but to my knowledge this hasn't been used with an actual lesson yet). 

With these considerations in mind, I'm comfortable leaving it to your discretion which exercises are accepted, but I would also like to revisit this in ~6 months to see if there are strategic ways we can capitalize on extra sets of eyes to contribute in targeted and meaningful ways.

**Comment by weaverbel** [comment] 2017-04-13 01:39
I would be in favour of limiting lessons they can contribute to (in future) as the ones that appear on this page (with the exception of instructor training): https://software-carpentry.org/lessons/ or this page: http://www.datacarpentry.org/lessons/

**Comment by maneesha** [comment] 2017-04-13 12:07
@weaverbel  The issue is that there are Contributed Lessons at the bottom of https://software-carpentry.org/lessons/ -- do we allow contributions to those?  

I'd like to reiterate my earlier comment and @k8hertweck 's suggestion that we revisit this to be sure we are getting targeted and meaningful contributions, rather than rote homework checkoffs.

Note for example there are DC lessons in development that it may actually be good to have someone review and contribute to - even if they are not yet part of our core offerings.

**Comment by raynamharris** [comment] 2017-04-13 18:21
Would it be helpful to ask that the trainees use 1 specific lesson for both their teaching demo and their checkout?

One thing I see a lot with the demo session is that some of the lesson materials are fabulous and others could use a revamp.

Or, we could provide two lists: a great lessons list for demo and a improvement-wanted list for lesson contribution

**Comment by tracykteal** [comment] 2017-04-13 18:34
Thanks @ErinBecker for bringing this up. I think the goal of checkout is to 1) show that they know how to contribute to lessons and 2) that they gain some more familiarity with the lessons they're likely to teach. So, it makes sense to me to have people contribute to the ones we're actively teaching. Also the 'non teaching' ones don't necessarily have active maintainers who will be able to work with the contributor on their PR. 

So, I think restricting contributions to 'Lessons' and not 'Contributions' makes sense. 

I know we're working on contributor guidelines and onboarding information, and I think having some clearer 'How to Contribute' guidelines will help here too. Ideally, we'd like people to contribute in the way we would want people to contribute to open source - looking at open issues as one of the first steps. I think the [Bug BBQ How-to-Contribute](https://github.com/datacarpentry/lesson-release/blob/master/how-to-contribute.md) document helped with the Bug BBQ, and could be a starting place for a New Instructors How-to-Contribute document.

**Comment by weaverbel** [comment] 2017-04-13 20:34
I like @raynamharris's idea of identifying lessons we would like input to or improvement on - that seems like a good plan as it saves them the bother of trying to figure out what lessons they should be targeting, and there is not much point getting input on lessons that are already in good shape. 

I also second @tracykteal's idea of creating 'How to Contribute' guidelines so that people know exactly what to do. I have found from my experience with different groups checking out that some people need a lot of direction about these tasks, even though the instructions and next steps are very clear.

**Comment by jduckles** [comment] 2017-05-11 23:48
@ErinBecker Closing since I think this discussion has run its course. Please reopen if you'd like to to go on.

**Closed as completed by jduckles** 2017-05-11 23:48 UTC
