### ISSUE TITLE
Add a 'welcome page' as an overview for new community members

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/website-archive#379] opened 2016-05-10 13:40 UTC
Suggestion that came from @swaldman3 and others on https://github.com/swcarpentry/board/issues/111

What would be good to include on this page?

**Comment by k8hertweck** [comment] 2016-05-10 13:53
General "how-to" for getting involved:
- link to community calendar (and explanation of lab meetings, instructor discussion?)
- link to mailing lists

**Comment by swaldman3** [comment] 2016-05-10 13:53
- What sorts of help are wanted/needed (in general terms; I'm not suggesting that this should need updating). Note that since this is not primarily a software project, "help" does not just mean git commits.
- How to find an issue to work on, how to submit changes, and who (and how/where) to ask for help or clarifications. For most projects I'd include an introduction to github, etc., but that may be a tad redundant for SWC for obvious reasons. Or maybe it isn't?
- What the various communication channels are, and how they're used.
- Expected behavior on these channels, and on the project in general
- (Who is who???) (not sure about this one)

Possibly other stuff :-)

As mentioned elsewhere, I'm happy to do my bit by drafting this, but I'm not quite sufficiently involved to know the detail of what it should say...

**Comment by gdevenyi** [comment] 2016-05-10 14:17
- a request to make an attempt to read the history of discussions on a repo before making a change

**Comment by bsmith89** [comment] 2016-05-10 18:29
@gdevenyi How would this work?  Most of the repos have hundreds or thousands of commits and quite a number of closed issues.  Would a `CHANGES.md` be helpful?

Most of the teaching guides (`instructors.md`) have some discussion of "Lesson Philosophy", describing why the lesson is designed the way it is.  Should reading this be a (either suggested or mandatory) prerequisite for contributing?

**Comment by ctb** [comment] 2016-05-11 13:34
Does anyone mind if I pass this issue on to the discuss list along with https://github.com/swcarpentry/board/issues/114?

**Comment by tracykteal** [comment] 2016-05-11 13:39
Sure, that would be great.

**Comment by karawoo** [comment] 2016-05-11 16:32
I like the idea of the welcome page. I think it should be fairly concise: mission statement, code of conduct (perhaps with a clarification that this applies to all email lists, issue threads, etc.), link to FAQ and description of where to go to find more information or ask questions. There could be more, but I'd suggest not making it a comprehensive resource of anything a new person might want to know, because the longer the welcome page is the less likely people are to actually read it thoroughly.

**Comment by gdevenyi** [comment] 2016-05-11 17:06
@bsmith89 yes right, a changes or some type of document which notes "we have argued about topic X many times, for now, we stick with this, please check with the maintainers before making changes around this topic"

**Comment by wking** [comment] 2016-05-11 18:32
On Wed, May 11, 2016 at 10:06:15AM -0700, Gabriel A. Devenyi wrote:

> … or some type of document which notes "we have argued about topic X
> many times, for now, we stick with this, please check with the
> maintainers before making changes around this topic"

I think the frequently-argued-issues docs are addressed by the stub in
[1](https://github.com/swcarpentry/lesson-example/pull/21).

**Comment by jduckles** [comment] 2016-12-02 17:06
This is what http://software-carpentry.org/join/ tries to be, but maybe we should move some of this content to the main page of the website.

**Comment by ErinBecker** [comment] 2018-06-13 20:48
Closed with https://carpentries.org/community/ and https://carpentries.org/join/

**Closed as completed** 2018-06-13 20:49 UTC
Labels: help wanted
